project:
  type: website
  output-dir: _site
  resources:
    - app.html
    - darkheader.svg

website:
  title: "Llano"
  favicon: favicon.ico
  page-footer:
    left: "© 2026 Llano. All rights reserved. &nbsp;|&nbsp; Made Deep in the ❤️"
    right:
      - text: "hello@llano.io"
        href: "mailto:hello@llano.io"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
